### ISSUE TITLE
代码运行报错问题

### ISSUE THREAD

**Issue by zijialee** [tweedlemoon/LSFforSeg#1]
<img width="1280" alt="屏幕截图 2023-12-02 231106" src="https://github.com/tweedlemoon/LSRPR/assets/95079788/4a2923a7-6260-4330-81a8-500eca1e9385">
请问这里的代码是不是有点问题？我下载完DRIVE数据集后运行代码，但是下面报错说test中没有01_manual1.gif文件，但是DRIVE数据集中的test里压根就没有manual的文件夹，只有training中才有1st_manual文件夹，应该怎么修改呢？

**Comment by tweedlemoon** [comment]
你的DRIVE数据集不完整

**Comment by zijialee** [comment]
还想请教一下
1.第一阶段100个epoch后，准备进行第二阶段，这个时候加载第一阶段训练完成的模型为pretrained，是不是epoch还是设为100就行？论文中是说第二阶段需要200个epoch，我的理解是不是两个阶段合起来才是200epoch，各100epoch？
2.在直接加载第一阶段训练完成的模型为pretrained后，这个时候学习率是重新初始化为0.01吗？还是得初始化为第一阶段完成时候的学习率
3.我第一阶段已经完成，准备进行第二阶段，请问这样的参数设置，有问题吗？
<img width="848" alt="屏幕截图 2024-03-07 220404" src="https://github.com/tweedlemoon/LSRPR/assets/95079788/c76c7db4-f77d-48db-a03e-8b857193dec1">

**Comment by tweedlemoon** [comment]
1：是的，第一阶段训练完成的模型即为pretrained，对于epoch数量并没有具体定死，根据不同的迭代取到最好的结果即可。
2：这个代码的学习率迭代策略是Warmup，是DeepLab这个系列工作的学习率迭代策略，理论上任何学习率迭代策略都可以，我训练是以0.01重新开始，但不排除有更好的值。
3：batch_size至少设置为2或4，否则网络收敛可能出现问题。

**Comment by zijialee** [comment]
好的，非常感谢！

**Comment by zijialee** [comment]
求助：
batchsize设为4了，但是也一直跑不到文中的结果，各项指标都远远低于文中的结果，mIoU一般都是在80左右，能到80都比较少，acc只能到95左右，这该怎么办？文中的结果是多次实验中，只取了一次最好的结果吗？但是即使是这样我也一直运行不出这种效果

**Comment by tweedlemoon** [comment]
对于DRIVE数据集的验证集，有两位专家进行标注，文中使用manual2作为标准答案，即在inference.py中修改最开始的Manual为manual2，在inference.py的main函数里解开compute_index的注释来计算指标。
在以Attention UNet作为分割网络辅以水平集时，准确率Acc一般在97左右，mIoU一般在84左右，误差基本不超过1%。文中的值是我训练过程中某一个指标最高历史值，无法做到某一次训练结果中所有指标都达到最高。
我这里有一个各个指标都相对较优的结果，https://cloud.189.cn/t/RfiIreIJfaqu （访问码：oo2e），有效期7天，将该pth放在inferece.py里就能看到对应的结果。
对于CHASE_DB1数据集，由于该数据集没有分训练集和测试集，因此各个文章对它的结果也出现巨大差异，衡量标准参差不齐，暂时无法讨论。
最后，训练深度神经网络既看技术也看运气，祝你好运！

**Comment by zijialee** [comment]
我看不都是用manual1来作为标准答案的吗？你是拿manual2的去跟别人manual1比较吗
