### ISSUE TITLE
代码与论文

### ISSUE THREAD

**Issue by hh12345h** [tweedlemoon/LSFforSeg#3]
<img width="692" alt="屏幕截图 2024-03-09 220103" src="https://github.com/tweedlemoon/LSRPR/assets/162812400/a0e90461-5528-45aa-b8c3-cdf4d00760ce">
<img width="432" alt="屏幕截图 2024-03-09 220738" src="https://github.com/tweedlemoon/LSRPR/assets/162812400/1a9fc2ec-66c4-4afe-9caf-e66cd9bf0699">

代码中计算水平集损失的时候，都是用到softmax之后的值，也就是论文中的$z_i(x ; \Theta)$，没有看出哪里是用到了$y_i(x ; \Theta)$，是论文有出入还是代码的问题呢？

**Comment by tweedlemoon** [comment]
论文和代码都是这样写的
z是feature map上的值，是神经网络的原始输出，y是过了softmax之后的概率值
不理解的话去对照文中的图来理解
代码中的measurement就是z

**Comment by hh12345h** [comment]
在你的论文中，z是feature map上的值没错。但是在你的代码中，你说measurement就是z，而measurement来源于back_ground和fore_ground，back_ground和fore_ground又是来源于softmaxed，softmaxed则是将feature map上的值经过了softmax层，这哪里符合论文中“z是feature map上的值”。
最简单来看，debug代码，看measurement的输出，全部都是在[-1,1]内的，是不可能有下图z=-3的可能的。
![屏幕截图 2024-04-07 212620](https://github.com/tweedlemoon/LSRPR/assets/162812400/dd78e1e6-d8ce-40c2-9c59-58338e9b5a23)

**Comment by tweedlemoon** [comment]
我懂你的意思了
我初步看是代码的问题
measurement应该直接用net_output['out']来算
我确认一下，然后会对代码进行修改

**Comment by hh12345h** [comment]
好的，谢谢

**Comment by hh12345h** [comment]
还有一个问题，文中其实也有提到将输出转化到[-0.5,0.5]，但是看代码其实好像没这个操作，代码似乎是直接转化为[-1,1]，这会有什么区别吗

**Comment by tweedlemoon** [comment]
你提到的应该是相关工作里的，那是前人的方法。我使用的方法是从第三章开始的，并没有这方面的操作。

**Comment by hh12345h** [comment]
好的

**Comment by hh12345h** [comment]
抱歉再请教一个问题，打扰了。就是保存模型的时候，为什么在验证集上根据的是dice loss小的来保存，而不根据文中提出的新的总loss（包括交叉熵，Dice以及水平集损失）来保存模型？

**Comment by tweedlemoon** [comment]
水平集损失不代表分割准确性，所以不能带它。
能准确衡量分割准确性的只有交叉熵和Dice，二者选一即可，我这边选的是Dice因为它比交叉熵更综合一点。
用交叉熵更小的模型也是没有问题的。

**Comment by hh12345h** [comment]
那你是直接就根据dice来选择保存的权重吗？有看验证集上的其他指标吗？

**Comment by tweedlemoon** [comment]
对，使用Dice来选择保存的权重。
保存权重只能使用一个指标来衡量，还是我上面说的，综合性最好的就是Dice。
其它指标一般会造成自己特别高，其它特别低的情况，你可以自己试试。

**Comment by hh12345h** [comment]
好嘞

**Comment by hh12345h** [comment]
<img width="364" alt="屏幕截图 2024-04-09 153608" src="https://github.com/tweedlemoon/LSRPR/assets/162812400/9c482537-4986-4538-bbd0-8e360c33f5b4">
监督阶段，这个是不是应该用target呢，用argmaxed不合理吧，argmaxed相当于没有用到监督，还是在预测这个位置是前景或者背景

**Comment by tweedlemoon** [comment]
往下看

**Comment by hh12345h** [comment]
<img width="561" alt="屏幕截图 2024-04-09 155238" src="https://github.com/tweedlemoon/LSRPR/assets/162812400/50e77732-a116-4a17-8113-53d94f250014">
我知道你下面有用到target，我说的是measurement_multi_channel会不会有问题？measurement_multi_channel是来自measurement，而measurement = torch.where(argmaxed == 0, back_ground, fore_ground)，我的意思是这里是不是应该换为
measurement = torch.where(target == 0, back_ground, fore_ground)

**Comment by tweedlemoon** [comment]
不应该。
两个阶段分别做的事情不一样，第一阶段的水平集损失是不加入target的，文中说得也很清楚。

**Comment by hh12345h** [comment]
<img width="372" alt="屏幕截图 2024-04-11 182407" src="https://github.com/tweedlemoon/LSRPR/assets/162812400/243f4cd2-35d6-4120-86f3-94b44179cab9">

请教一下，为什么需要把背景这个设置为负值呢？有什么作用？此外，还有一个新手疑问，unet最终的输出会有两个通道的值，那怎么能确定哪一个是前景哪一个是背景呢？随便指定吗？
Emm...，新手学习，想把每个地方都搞明白……
