### ISSUE TITLE
论文疑问

### ISSUE THREAD

**Issue by linshuyu1** [tweedlemoon/LSFforSeg#4]
<img width="425" alt="屏幕截图 2024-03-17 103227" src="https://github.com/tweedlemoon/LSRPR/assets/163702879/9a43f2c2-6fe1-4fa3-bf91-f68f741fa5e5">
请问这里没有LS损失的原架构结果，是不是通过文章提出的模型自己运行出来的？也就是只用了dice与交叉熵损失？如果是的话，是不是直接运行200epoch即可，也不需要分两阶段了？
如果上面的猜测都是对的话，我在r2unet原始框架上运行的结果远远达不到文中的效果，是在训练时有什么技巧没注意到吗，想询问一下怎么训练出来的这个结果？

**Comment by tweedlemoon** [comment]
这个数据取自于网上的深度学习社区，我自己使用Dice和交叉熵训练r2unet的时候准确率是0.9695，与网上的数据相差0.0016，基本可以看做是误差，为了体现模型的最高性能，我采用了网上的数据。
r2unet在与本文的LSloss结合的过程中出现了精度下降和结果不稳定的现象，换句话说它并不适合放在这个框架里作为分割网络，它只是我在实验中的一个排除项，这也不是本文的重点，本文的重点是使用LS损失提升细微血管的连续性以及分割结果的平滑性。

**Comment by linshuyu1** [comment]
可以分享一下这些数据都是在哪里获取的吗

**Comment by tweedlemoon** [comment]
paperwithcode, hugging face, kaggle, openmmlab
