### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by linshuyu1** [tweedlemoon/LSFforSeg#5]
代码运行的时候，如果损失函数不使用水平集损失，只用交叉熵损失和dice损失，这个时候就没有stage1和stage2之分了吧？用作对比的时候是不是直接训练200个Epoch即可

**Comment by linshuyu1** [comment]
halo你好，请问能解决一下我这疑问吗

**Comment by tweedlemoon** [comment]
不使用就是原网络训练，也没有阶段之分
